version: "3.2"
services:
  nodejs:
    build: .
    networks:
      - frontend
      - backend
      - microservices-fiap_kafka
    environment:
      - MYSQL_HOST=mba-mysql-favorites
      - MYSQL_USER=admin
      - MYSQL_PASS=admin123
      - MYSQL_DB=mba_microservices_favorites
      - KAFKA_HOST=kafka:29092
    volumes:
      - ./www/:/var/www/html/
    ports:
      - "4010:4010"
    container_name: mba-favorites-service
  mysql:
    image: mysql:5.7
    ports:
      - 3310:3306
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin123
      - MYSQL_DATABASE=mba_microservices_favorites
    volumes:
      - mysql_favorite:/var/lib/mysql
    container_name: mba-mysql-favorites
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.7
    depends_on:
      - mysql
    networks:
      - backend
    ports:
      - "30002:80"
    environment:
      - PMA_HOST=mba-mysql-favorites
      - PMA_PORT= 3310
    volumes:
      - /sessions
    container_name: mba-phpmyadmin-favorites
networks:
  frontend:
  backend:
  microservices-fiap_kafka:
    external: true
volumes:
  mysql_favorite:
