version: "3.2"
services:
  nodejs:
    build: .
    networks:
      - frontend
      - backend
      - sb
      - microservices-fiap_kafka
    environment:
      - MYSQL_HOST=mba-product-db
      - MYSQL_USER=admin
      - MYSQL_PASS=admin123
      - MYSQL_DB=mba_microservices_amazon
      - KAFKA_HOST=kafka:29092
    volumes:
      - ./www/:/var/www/html/
    ports:
      - "3000:3000"
    container_name: mba-product-service
  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin123
      - MYSQL_DATABASE=mba_microservices_amazon
    volumes:
      - mysql_product:/var/lib/mysql
    container_name: mba-product-db
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.7
    depends_on:
      - mysql
    networks:
      - backend
    ports:
      - "30002:80"
    environment:
      - PMA_HOST=mba-mysql-app
      - PMA_PORT= 3306
    volumes:
      - /sessions
    container_name: mba-phpmyadmin-app
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    networks:
      - sb
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'bitnami/kafka:latest'
    container_name: 'kafka'
    networks:
      - sb
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
networks:
  frontend:
  backend:
  sb:
    driver: bridge
  microservices-fiap_kafka:
    external: true
volumes:
  mysql_product:
